=== gvetticaden/stream-simulator/src/main/resources/xsd/kml.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.opengis.net/kml/2.2"
xmlns="http://www.opengis.net/kml/2.2" elementFormDefault="qualified">

<xs:element name="kml" type="kml"  />

<xs:complexType name="kml">
	<xs:sequence>
		<xs:element name="Document" type="document" minOccurs="1" maxOccurs="1"/>
	</xs:sequence>
</xs:complexType>


<xs:complexType name="document" >
  <xs:sequence> 	
  	<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
  	<xs:element name="Placemark" type="placemark" minOccurs="0" maxOccurs="unbounded"/>  
  	<xs:element name="Style" type="style" minOccurs="0" maxOccurs="1"/>  
  </xs:sequence>
</xs:complexType>


<xs:complexType name="placemark">
	<xs:sequence>
		<xs:element name="styleUrl" type="xs:string"/>
		<xs:element name="name" type="xs:string"/>
		<xs:element name="Point" type="point" minOccurs="1" maxOccurs="1"/>
	</xs:sequence>
</xs:complexType>


<xs:complexType name="point">
	<xs:sequence>
		<xs:element name="coordinates" type="xs:string"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="style">
	
	<xs:sequence>
		<xs:element name="IconStyle" type="iconstyle"/>
	</xs:sequence>
	<xs:attribute name="id" use="required"/>
</xs:complexType>


<xs:complexType name="iconstyle">
	<xs:sequence>
		<xs:element name="color" type="xs:string"/>
		<xs:element name="scale" type="xs:string"/>
		<xs:element name="Icon" type="icon"/>
	</xs:sequence>
	
</xs:complexType>

<xs:complexType name="icon">
	<xs:sequence>
		<xs:element name="href" type="xs:string"/>
	</xs:sequence>
</xs:complexType>




</xs:schema>

=== gvetticaden/stream-simulator/src/test/resources/TestRoute.xml
<?xml version='1.0' encoding='UTF-8'?>
<kml xmlns="http://www.opengis.net/kml/2.2"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.opengis.net/kml/2.2 kml.xsd">
	<Document>
		<name>Untitled layer</name>
		<Placemark>
			<styleUrl>#icon-503-DB4436</styleUrl>
			<name>Point 1</name>
			<Point>
				<coordinates>-74.12402629852295,40.62177060472069,0.0</coordinates>
			</Point>
		</Placemark>
		<Placemark>
			<styleUrl>#icon-503-DB4436</styleUrl>
			<name>Point 3</name>
			<Point>
				<coordinates>-74.13187980651855,40.621184274191414,0.0</coordinates>
			</Point>
		</Placemark>
		<Placemark>
			<styleUrl>#icon-503-DB4436</styleUrl>
			<name>Point 4</name>
			<Point>
				<coordinates>-74.1313648223877,40.62659134949805,0.0</coordinates>
			</Point>
		</Placemark>
		<Placemark>
			<styleUrl>#icon-503-DB4436</styleUrl>
			<name>Point 5</name>
			<Point>
				<coordinates>-74.12939071655273,40.63378924635125,0.0</coordinates>
			</Point>
		</Placemark>
		<Placemark>
			<styleUrl>#icon-503-DB4436</styleUrl>
			<name>Point 6</name>
			<Point>
				<coordinates>-74.1346263885498,40.63616666172068,0.0</coordinates>
			</Point>
		</Placemark>
		<Placemark>
			<styleUrl>#icon-503-DB4436</styleUrl>
			<name>Point 7</name>
			<Point>
				<coordinates>-74.1317081451416,40.64040020550189,0.0</coordinates>
			</Point>
		</Placemark>
		<Placemark>
			<styleUrl>#icon-503-DB4436</styleUrl>
			<name>Point 8</name>
			<Point>
				<coordinates>-74.13930416107178,40.6398140385301,0.0</coordinates>
			</Point>
		</Placemark>
		<Placemark>
			<styleUrl>#icon-503-DB4436</styleUrl>
			<name>Point 9</name>
			<Point>
				<coordinates>-74.16629791259766,40.640367640805145,0.0</coordinates>
			</Point>
		</Placemark>
		<Placemark>
			<styleUrl>#icon-503-DB4436</styleUrl>
			<name>Point 10</name>
			<Point>
				<coordinates>-74.16646957397461,40.63369154253879,0.0</coordinates>
			</Point>
		</Placemark>
		<Style id='icon-503-DB4436'>
			<IconStyle>
				<color>ff3644DB</color>
				<scale>1.1</scale>
				<Icon>
					<href>http://www.gstatic.com/mapspro/images/stock/503-wht-blank_maps.png</href>
				</Icon>
			</IconStyle>
		</Style>
	</Document>
</kml>
